export const demoIds = {
  semester: 'demo-semester-current',
  courses: [
    'demo-course-seg3101',
    'demo-course-csi3105',
    'demo-course-mat2377',
    'demo-course-csi3131',
  ],
  assessments: [
    'requirements',
    'prototype',
    'seg-midterm',
    'seg-final',
    'seg-quiz',
    'seg-project',
    'algorithms',
    'csi-quiz',
    'csi-midterm',
    'csi-final',
    'probability',
    'mat-quiz',
    'mat-midterm',
    'mat-final',
    'processes',
    'os-lab',
    'os-midterm',
    'os-final',
  ].map((id) => `demo-assessment-${id}`),
  tasks: [
    'requirements',
    'algorithms',
    'probability',
    'reading',
    'processes',
    'office-hours',
    'notes',
    'study-plan',
  ].map((id) => `demo-task-${id}`),
  events: ['study-session', 'office-hours', 'coffee'].map((id) => `demo-event-${id}`),
  schedules: [
    'seg-mon',
    'seg-wed',
    'csi-tue',
    'csi-thu',
    'mat-mon',
    'mat-fri',
    'os-wed',
    'os-fri',
  ].map((id) => `demo-schedule-${id}`),
};
